#!/usr/bin/env node
/**
 * Self-hosts the two site faces.
 *
 *   npm run fonts
 *
 * Why not just link Google Fonts: that link is a render-blocking stylesheet on
 * a third-party origin, and it opens a request chain the browser cannot start
 * until the HTML has parsed - HTML, then the CSS, then the font files, on a
 * connection it has to negotiate first. On a throttled mobile connection that
 * measured about 2.3 seconds of blocked rendering.
 *
 * Serving the woff2 files from our own origin removes the third party, the
 * blocking stylesheet and two of the three round trips.
 *
 * Only the latin subset is taken. The site is English; pulling cyrillic,
 * greek and vietnamese would triple the bytes for glyphs nothing renders.
 *
 * Output: public/fonts/*.woff2 and src/styles/fonts.css
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = dirname(HERE);
const OUT = join(ROOT, 'public', 'fonts');
const CSS_OUT = join(ROOT, 'src', 'styles', 'fonts.css');

/**
 * Only the weights the CSS actually sets.
 *
 * Barlow 500 was dropped after an audit: the single `font-weight: 500` rule in
 * the site inherits Inter, not Barlow, so that face was 21 KB downloaded on
 * every page and never used to draw a glyph. Inter is a variable font, so one
 * file serves 400/500/600 - asking for extra Inter weights adds nothing.
 */
const GOOGLE_CSS =
  'https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@600;700&family=Inter:wght@400&display=swap';

// Google serves woff2 only to browsers that advertise support.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const c = {
  dim: (s) => `\x1b[2m${s}\x1b[0m`,
  green: (s) => `\x1b[32m${s}\x1b[0m`,
  bold: (s) => `\x1b[1m${s}\x1b[0m`,
};

function slug(family, weight) {
  return `${family.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${weight}`;
}

async function main() {
  console.log(c.bold('\nSelf-hosting fonts\n'));

  const res = await fetch(GOOGLE_CSS, { headers: { 'user-agent': UA } });
  if (!res.ok) throw new Error(`Google Fonts returned ${res.status}`);
  const css = await res.text();

  mkdirSync(OUT, { recursive: true });

  const faces = [];
  const seenUrl = new Map();

  for (const block of css.split('@font-face').slice(1)) {
    const range = block.match(/unicode-range:\s*([^;]+);/)?.[1] ?? '';
    // U+0000-00FF marks the latin block; the others are subsets we do not set.
    if (!range.includes('U+0000-00FF')) continue;

    const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
    const weight = block.match(/font-weight:\s*(\d+)/)?.[1];
    const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
    if (!family || !weight || !url) continue;

    // Inter ships as one variable file that every weight points at; download
    // it once and let the @font-face rules share it.
    let file = seenUrl.get(url);
    if (!file) {
      file = `${slug(family, weight)}.woff2`;
      const bin = await fetch(url, { headers: { 'user-agent': UA } });
      if (!bin.ok) throw new Error(`${url} returned ${bin.status}`);
      const buf = Buffer.from(await bin.arrayBuffer());
      writeFileSync(join(OUT, file), buf);
      seenUrl.set(url, file);
      console.log(
        `  ${c.green('get ')}  ${file} ${c.dim(Math.round(buf.length / 1024) + 'KB')}`,
      );
    }

    faces.push({ family, weight, file, shared: seenUrl.get(url) !== null });
  }

  const rules = faces
    .map(
      (f) => `@font-face {
  font-family: '${f.family}';
  font-style: normal;
  font-weight: ${f.weight};
  font-display: swap;
  src: url('/fonts/${f.file}') format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA,
    U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193,
    U+2212, U+2215, U+FEFF, U+FFFD;
}`,
    )
    .join('\n\n');

  writeFileSync(
    CSS_OUT,
    `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.
   Re-run \`npm run fonts\` to refresh.

   Self-hosted so the site does not block first render on a third-party
   stylesheet. font-display: swap keeps text visible while a face loads. */

${rules}
`,
  );

  console.log(
    c.bold('\nDone.') +
      ` ${seenUrl.size} files, ${faces.length} @font-face rules -> src/styles/fonts.css\n`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
